### ISSUE TITLE
Can not build/upload

### ISSUE THREAD

**Issue by bjoshuanoah** [sybip/gtm-lab#1] opened 2021-03-01 23:00 UTC
I'm having two issues which prevent me from building/verifying

1. TimeLib.h

`gtmRadio.cpp:8:10: fatal error: TimeLib.h: No such file or directory
 #include <TimeLib.h>
          ^~~~~~~~~~~
compilation terminated.
exit status 1
TimeLib.h: No such file or directory
`
Upon further searching I found that it should be `include <Time.h>`

2. esp_log.h
`gtmRadio.cpp:8:10: fatal error: TimeLib.h: No such file or directory
 #include <TimeLib.h>
          ^~~~~~~~~~~
compilation terminated.
exit status 1
TimeLib.h: No such file or directory`

I'm getting the same errors on "playharder.cpp"

I made sure to download and install the dependencies from here: 
https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam

This is the board I'm working with: 
https://www.amazon.com/gp/product/B08GK8JP7Y/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

**Comment by bjoshuanoah** [comment] 2021-03-02 04:30
Sorry, I included the wrong error log for esp_log.h But it's the same. No such file or directory "esp_log.h"

**Comment by sybip** [comment] 2021-03-02 12:06
Excellent choice on the hardware - same model that I use! :)

I can see a few issues here, mostly the result of incorrect/incomplete documentation at my end - my apologies for this. I have updated the README.

> No such file or directory "esp_log.h"

It means that Arduino doesn't know we're compiling for an ESP target. You need to select the correct board ("T-Beam" in your case) from Arduino's *Tools > Board* menu.
If you don't have a "T-Beam" option in the list, you may need to (re)install the ESP32 support files in Arduino. See for instructions:
https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md

> TimeLib.h: No such file or directory

This was another error in my documentation (fixed now). You need to install the "**Time** by Michael Margolis" library from Arduino's *Tools > Manage Libraries* menu, this will fix the TimeLib.h error.

>  Upon further searching I found that it should be include <Time.h>

The header files `TimeLib.h` and `Time.h` (in the Margolis library context) used to be equivalent/interchangeable, however the latter has been deprecated due to a name conflict. 
Discussion: https://forum.arduino.cc/index.php?topic=451360.0

Good luck!

**Comment by sybip** [comment] 2021-03-02 12:11
Ah, one more thing:

> I made sure to download and install the dependencies from here:
> https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam

We don't use any of those libraries at this stage, and it may actually be safer to put them away for the time being. :)

**Comment by bjoshuanoah** [comment] 2021-03-02 20:32
I was able to install everything I needed. The `Time by Michael Margolis` was way on the bottom and I had to scroll quite a bit to be able to install it. :)

I'm going to have to spend some time learning about how all of these work. I'm new to arduino. Not sure how to test the relay mode just yet as that's what my main goal on this is.

**Closed as completed** 2021-03-02 20:32 UTC

**Comment by bjoshuanoah** [comment] 2021-03-02 20:40
Hey, can we do a zoom session so I can learn a little more on how we might want to implement relay mode?

**Comment by sybip** [comment] 2021-03-02 22:47
To enable the experimental relay mode, just type `!sr1` in the serial console and press Enter. It should respond `GTMLAB: RELAYING is now ON` and that's it. :)

Before you do that, though, you should first make sure you can send and receive messages.
Try running your gtm-lab *in the presence* of some goTenna traffic and check for `RX_MSG` lines in the console. These indicate that gtm-lab is receiving radio traffic correctly.
Secondly, check for output lines that say `GTMLIB: RELAYMSG (OFF)`, which indicate that the gtm-lab *would have relayed* the message in a relaying-enabled scenario.

Once you have this functionality confirmed, you can enable the relay (`!sr1`) and see how it works for you. 

I'm sorry, I don't have zoom, but please feel free to open as many issues as you need - even if it's just to ask a question.
